== API- und Sprachänderungen

=== Milling Project Coin

==== Aufgabe:

* Probiere das Problem mit SafeVarargs selbst aus und teste die Möglichkeit, die Annotation an privaten Methoden anzuhängen

.SafeVarargs
[source,java]
----
public class SafeVarargs {

    static <T> T[] asArray(T... args) {
        return args;
    }

    static <T> T[] arrayOfTwo(T a, T b) {
        return asArray(a, b);
    }


    public static void main(String[] args) {
        String[] sArr = arrayOfTwo("Hello", "World");
        System.out.println(Arrays.asList(sArr));

    }

}
----

* Baue ein try-with-resources und baue es um, so dass es eine bestehende Variable weiter verwendet

.SafeVarargs
[source,java]
----
try (BufferedReader reader = new BufferedReader(new InputStreamReader(TryWithResources.class.getResourceAsStream("hello.txt")))) {
	System.out.println(reader.readLine());
} catch (IOException e) {
	e.printStackTrace();
}
----

* Verwende den Diamond Operator bei der Zuweisung zu generischen Typen und versuche das auch mit anonymen inneren Klassen

* Baue ein Interface mit Default-Methoden und erstelle eine private Methode

.SafeVarargs
[source,java]
----
public interface Hello {
    String makeHello(String name);

    default void sayHello(String name) {
	    print(makeHello(name));
    }

    default void print(String string) {
	    System.out.println(string);
    }
}
----

* versucht den Unterstrich "_" als Bezeichner zu verwenden. Mit welchen Trick könnt ihr trotzdem Unterstriche für Variablennamen verwenden?


=== Collection Factory Methods

==== Aufgaben

* Erweitere die Klasse collection/factories/CollectionFactories.java
* Erzeuge gefüllte Listen und Sets mit den neuen Factory-Methoden im List und Set-Interface
** versuche diese Listen/Sets zu ändern
** was ist der Unterschied zw. Unmodifiable und Immutable und waren sind die erzeugten Listen/Sets nur Unmodifiable?
* Erzeuge eine Map mit den Nachnamen der Teilnehmer als Key und dem jeweiligen Vornamen als Value
** Erzeuge eine Map mit beispielhaften Werten mittels Entry-Instanzen

* Erweitere die Klasse collection/factories/CollectionsCopy.java
** erstelle in der Methode collectionsCopy() eine unveränderbare Kopie der Liste `strings`, versuche das Ergebnis zu verändern (neuen Wert hinzufügen) und teste, dass das Ändern der Originalliste keine Auswirkungen auf die Kopie hat
** erstelle in der Methode mapCopy() eine unveränderbare Kopie der Map, versuche die neue Map zu verändern und prüfe, dass Änderungen an der alten Map sich nicht auf die neue auswirken

=== Änderungen an Optional

==== Aufgaben

* ergänze die Klasse optionals/OptionalUpdate.java
* teste die neue Methode `ifPresentOrElse()` und gib beinem leeren Optional die Info "kein Wert" aus
* erzeuge ein alternatives Optional, wenn es keinen Wert hat
* erzeuge einen Stream aus einem Optional
* lese den Wert aus einem Optional oder lass eine Exception werfen (`orElseThrow()`)
